# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inception_inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19inception_inference.proto\x12\x05proto\"(\n\x10InceptionRequest\x12\x14\n\x0cjpeg_encoded\x18\x01 \x01(\x0c\"3\n\x11InceptionResponse\x12\x0f\n\x07\x63lasses\x18\x03 \x03(\t\x12\r\n\x05score\x18\x02 \x03(\x02\x32Q\n\x10InceptionService\x12=\n\x08\x43lassify\x12\x17.proto.InceptionRequest\x1a\x18.proto.InceptionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inception_inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INCEPTIONREQUEST._serialized_start=36
  _INCEPTIONREQUEST._serialized_end=76
  _INCEPTIONRESPONSE._serialized_start=78
  _INCEPTIONRESPONSE._serialized_end=129
  _INCEPTIONSERVICE._serialized_start=131
  _INCEPTIONSERVICE._serialized_end=212
# @@protoc_insertion_point(module_scope)
